# Generated by Django 5.0.6 on 2026-08-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_teammember_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='production_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands_as_production_coordinator', to='directory.teammember'),
        ),
    ]
