# Generated by Django 5.0.6 on 2026-08-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_brand_production_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='palette',
            field=models.ImageField(blank=True, null=True, upload_to='brands/palettes/'),
        ),
    ]
