# Generated by Django 5.0.6 on 2026-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_brand_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
