# Generated by Django 5.0.6 on 2026-08-23 16:30

import rush_republic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_freelancer_equipment_freelancer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='palette',
            field=models.ImageField(blank=True, null=True, upload_to='brands/palettes/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='models/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
    ]
