# Generated by Django 5.0.6 on 2026-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_brand_logo_alter_brand_palette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
