# Generated by Django 5.0.6 on 2026-09-22 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_modelprofile_skin_tone_modelprofile_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(110)]),
        ),
    ]
