# Generated by Django 5.0.6 on 2026-08-14 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('ADMIN', 'Admin'), ('SOCIAL_MEDIA', 'Social Media'), ('PRODUCTION_COORDINATOR', 'Production Co-Ordinator'), ('CLIENT_SERVICING', 'Client-Servicing'), ('SCRIPT_WRITER', 'Script Writer')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('brief', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('wrap_time', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoot_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shoot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('concept', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube Shorts'), ('TIKTOK', 'TikTok'), ('LINKEDIN', 'LinkedIn'), ('FACEBOOK', 'Facebook'), ('OTHER', 'Other')], default='INSTAGRAM', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('IDEA', 'Idea'), ('SCRIPTED', 'Scripted'), ('SHOT', 'Shot'), ('EDITING', 'Editing'), ('PUBLISHED', 'Published')], default='IDEA', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('reference_link', models.URLField(blank=True)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('shot_type', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('LIFESTYLE', 'Lifestyle'), ('CANDID', 'Candid'), ('GROUP', 'Group'), ('BTS', 'Behind The Scenes'), ('OTHER', 'Other')], default='PRODUCT', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SHOT', 'Shot'), ('RETOUCHING', 'Retouching'), ('DELIVERED', 'Delivered')], default='PLANNED', max_length=20)),
                ('reference_link', models.URLField(blank=True)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('ADMIN', 'Admin'), ('SOCIAL_MEDIA', 'Social Media'), ('PRODUCTION_COORDINATOR', 'Production Co-Ordinator'), ('CLIENT_SERVICING', 'Client-Servicing'), ('SCRIPT_WRITER', 'Script Writer')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SHOOT', 'Shoot Execution'), ('CLIENT', 'Client'), ('CREW', 'Crew'), ('BUDGET', 'Budget'), ('SCRIPT', 'Script'), ('TOOLING', 'Tooling / Portal')], default='GENERAL', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
                ('shoot_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='shootplan.shootplan')),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('DOP', 'Director of Photography'), ('CAMERA', 'Camera Operator'), ('PHOTOGRAPHER', 'Photographer'), ('EDITOR', 'Editor'), ('STYLIST', 'Stylist'), ('MAKEUP', 'Hair & Makeup'), ('PRODUCTION_ASSISTANT', 'Production Assistant'), ('SCRIPT_WRITER', 'Script Writer'), ('TALENT', 'Talent'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['call_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('CREW', 'Crew'), ('EQUIPMENT', 'Equipment'), ('LOCATION', 'Location'), ('TRAVEL', 'Travel'), ('CATERING', 'Catering'), ('PROPS', 'Props & Set'), ('POST_PRODUCTION', 'Post Production'), ('CONTINGENCY', 'Contingency'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AddIndex(
            model_name='shootplan',
            index=models.Index(fields=['department', 'status'], name='shootplan_s_departm_726af6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['department', 'status'], name='shootplan_f_departm_51c950_idx'),
        ),
    ]
