# Generated by Django 5.0.6 on 2026-08-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_teammember_designation'),
        ('shootplan', '0002_shootplan_status_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='crewmember',
            name='meal_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='meal_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='meals_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='person_type',
            field=models.CharField(choices=[('INTERNAL_TEAM', 'Internal Team'), ('FREELANCER', 'Freelancer'), ('MODEL', 'Model')], default='INTERNAL_TEAM', max_length=20),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='source_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.freelancer'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Agreed time out'),
        ),
        migrations.AddField(
            model_name='photo',
            name='notes_to_designer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes to editor'),
        ),
        migrations.AddField(
            model_name='reel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='photographer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shootplan',
            name='client_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shootplan',
            name='locations_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shootplan',
            name='models_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='call_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Agreed time in'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Shot description'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='concept',
            field=models.TextField(blank=True, verbose_name='Script'),
        ),
        migrations.CreateModel(
            name='PhotoBriefImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shootplan/photo-briefs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_gallery', to='shootplan.photo')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('map_url', models.URLField(blank=True)),
                ('permit_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='NOT_REQUIRED', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('access_notes', models.TextField(blank=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('budget_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Location cost (₹)')),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_locations', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, related_name='photo_briefs', to='shootplan.planlocation'),
        ),
        migrations.AddField(
            model_name='reel',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, related_name='reels', to='shootplan.planlocation'),
        ),
        migrations.CreateModel(
            name='PlanLocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LOCATION', 'Location photo'), ('BACKGROUND_REF', 'Preferred background')], default='LOCATION', max_length=20)),
                ('image', models.ImageField(upload_to='shootplan/locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_gallery', to='shootplan.planlocation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('from_directory', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('country_code', models.CharField(default='+91', max_length=6)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('agency', models.CharField(blank=True, max_length=150)),
                ('alt_contact', models.CharField(blank=True, max_length=100)),
                ('negotiated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('directory_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.modelprofile')),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_models', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='crewmember',
            name='source_plan_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shootplan.planmodel'),
        ),
        migrations.AddField(
            model_name='photo',
            name='assigned_models',
            field=models.ManyToManyField(blank=True, related_name='photo_briefs', to='shootplan.planmodel'),
        ),
        migrations.AddField(
            model_name='reel',
            name='assigned_models',
            field=models.ManyToManyField(blank=True, related_name='reels', to='shootplan.planmodel'),
        ),
        migrations.CreateModel(
            name='PlanModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MODEL', 'Model photo'), ('COSTUME', 'Costume photo'), ('COSTUME_COLOR_REF', 'Preferred costume color')], default='MODEL', max_length=20)),
                ('image', models.ImageField(upload_to='shootplan/models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_gallery', to='shootplan.planmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(blank=True, choices=[('STUDIO_INVENTORY', 'Studio Inventory'), ('RENTAL', 'Rental'), ('PURCHASE', 'Purchase'), ('CLIENT_PROVIDED', 'Client Provided'), ('OTHER', 'Other')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TO_SOURCE', 'To Source'), ('SOURCING', 'Sourcing'), ('READY', 'Ready')], default='TO_SOURCE', max_length=20)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='reel',
            name='assigned_props',
            field=models.ManyToManyField(blank=True, related_name='reels', to='shootplan.prop'),
        ),
        migrations.CreateModel(
            name='PropPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shootplan/props/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_gallery', to='shootplan.prop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shootplan/reels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_gallery', to='shootplan.reel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('expense_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('CAB', 'Cab'), ('FUEL', 'Fuel'), ('ACCOMMODATION', 'Accommodation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_expenses', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
