# Generated by Django 5.0.6 on 2026-08-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_teammember_designation'),
        ('shootplan', '0003_alter_photo_options_alter_reel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootplan',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoot_plans', to='directory.brand'),
        ),
    ]
