# Generated by Django 5.0.6 on 2026-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0004_shootplan_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootplan',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
