# Generated by Django 5.0.6 on 2026-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0005_alter_shootplan_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='assigned_props',
            field=models.ManyToManyField(blank=True, related_name='photo_briefs', to='shootplan.prop'),
        ),
        migrations.AddField(
            model_name='photobriefimage',
            name='category',
            field=models.CharField(choices=[('MOODBOARD', 'Moodboard'), ('WARDROBE', 'Wardrobe reference'), ('BACKGROUND', 'Background reference')], default='MOODBOARD', max_length=20),
        ),
        migrations.AddField(
            model_name='reelphoto',
            name='category',
            field=models.CharField(choices=[('STORYBOARD', 'Storyboard'), ('WARDROBE', 'Wardrobe reference'), ('BACKGROUND', 'Background reference')], default='STORYBOARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='department',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRODUCTION_HEAD', 'Production Head'), ('SOCIAL_MEDIA', 'Social Media Specialist'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('CLIENT_SERVICING', 'Client Servicing'), ('SCRIPT_WRITER', 'Script Writer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='planlocation',
            name='permit_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SECURED', 'Secured'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='prop',
            name='source',
            field=models.CharField(blank=True, choices=[('LENT', 'Lent'), ('RENTED', 'Rented'), ('OWNED', 'Owned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prop',
            name='status',
            field=models.CharField(choices=[('SECURED', 'Secured'), ('NOT_SECURED', 'Not Secured')], default='NOT_SECURED', max_length=20),
        ),
        migrations.AlterField(
            model_name='shootplan',
            name='department',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRODUCTION_HEAD', 'Production Head'), ('SOCIAL_MEDIA', 'Social Media Specialist'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('CLIENT_SERVICING', 'Client Servicing'), ('SCRIPT_WRITER', 'Script Writer')], max_length=30),
        ),
    ]
