# Generated by Django 5.0.6 on 2026-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0006_photo_assigned_props_photobriefimage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reel',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
