# Generated by Django 5.0.6 on 2026-08-20 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0008_crewmember_source_brand_role_alter_crewmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shoot_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='shootplan.shootplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
