# Generated by Django 5.0.6 on 2026-08-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0009_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelexpense',
            name='expense_type',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('CAB', 'Cab'), ('CAR_RENTAL', 'Car rental'), ('FUEL', 'Fuel'), ('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('ACCOMMODATION', 'Accommodation'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
