# Generated by Django 5.0.6 on 2026-08-23 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0010_alter_travelexpense_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReferenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_links', to='shootplan.photo')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
