# Generated by Django 5.0.6 on 2026-08-23 16:30

import rush_republic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0011_photoreferencelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobriefimage',
            name='image',
            field=models.ImageField(upload_to='shootplan/photo-briefs/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='planlocationphoto',
            name='image',
            field=models.ImageField(upload_to='shootplan/locations/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='planmodelphoto',
            name='image',
            field=models.ImageField(upload_to='shootplan/models/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='propphoto',
            name='image',
            field=models.ImageField(upload_to='shootplan/props/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='reelphoto',
            name='image',
            field=models.ImageField(upload_to='shootplan/reels/', validators=[rush_republic.validators.validate_image_file_size]),
        ),
    ]
