# Generated by Django 5.0.6 on 2026-08-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0012_alter_photobriefimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('RETURNED_FOR_CHANGES', 'Returned for Changes'), ('APPROVED', 'Approved')], default='DRAFT', max_length=25),
        ),
        migrations.AddField(
            model_name='reel',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reel',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reel',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reel',
            name='suggestions',
            field=models.TextField(blank=True, verbose_name='Latest return-for-changes suggestions'),
        ),
        migrations.AddField(
            model_name='reviewapproval',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='shootplan.reel'),
        ),
        migrations.AlterField(
            model_name='reviewapproval',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=20),
        ),
    ]
