# Generated by Django 5.0.6 on 2026-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0014_photo_approval_status_photo_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootplan',
            name='print_previewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
