# Generated by Django 5.0.6 on 2026-08-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0015_shootplan_print_previewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='assigned_freelancers',
            field=models.ManyToManyField(blank=True, related_name='photo_briefs', to='shootplan.crewmember'),
        ),
        migrations.AddField(
            model_name='reel',
            name='assigned_freelancers',
            field=models.ManyToManyField(blank=True, related_name='reels', to='shootplan.crewmember'),
        ),
    ]
