# Generated by Django 5.0.6 on 2026-08-31 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0016_photo_assigned_freelancers_reel_assigned_freelancers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='shootplan.reel')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
