# Generated by Django 5.0.6 on 2026-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0017_reelscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelscene',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
    ]
