# Generated by Django 5.0.6 on 2026-09-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0018_reelscene_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelphoto',
            name='category',
            field=models.CharField(choices=[('STORYBOARD', 'Storyboard'), ('WARDROBE', 'Wardrobe reference'), ('BACKGROUND', 'Background reference'), ('COLOR_PALETTE', 'Color Palette')], default='STORYBOARD', max_length=20),
        ),
    ]
