# Generated by Django 5.0.6 on 2026-09-01 06:28

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_freelancer_assignments(apps, schema_editor):
    """Preserve every existing Reel/Photo <-> freelancer pairing (previously a
    plain M2M with no per-pair data) as a through-model row before the next
    operations drop the old implicit join table -- role is left blank (per
    requirements: never invent a role for pre-existing assignments)."""
    Reel = apps.get_model('shootplan', 'Reel')
    Photo = apps.get_model('shootplan', 'Photo')
    ReelFreelancerAssignment = apps.get_model('shootplan', 'ReelFreelancerAssignment')
    PhotoFreelancerAssignment = apps.get_model('shootplan', 'PhotoFreelancerAssignment')

    for reel in Reel.objects.all():
        for crew_member_id in reel.assigned_freelancers.values_list('id', flat=True):
            ReelFreelancerAssignment.objects.get_or_create(reel_id=reel.id, crew_member_id=crew_member_id)

    for photo in Photo.objects.all():
        for crew_member_id in photo.assigned_freelancers.values_list('id', flat=True):
            PhotoFreelancerAssignment.objects.get_or_create(photo_id=photo.id, crew_member_id=crew_member_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0019_alter_reelphoto_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFreelancerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('CINEMATOGRAPHER', 'Cinematographer'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('SCRIPT_WRITER', 'Script Writer'), ('CAMERA_ASSISTANT', 'Camera Assistant'), ('PRODUCTION_HEAD', 'Production Head')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shootplan.crewmember')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_assignments', to='shootplan.photo')),
            ],
            options={
                'unique_together': {('photo', 'crew_member')},
            },
        ),
        migrations.CreateModel(
            name='ReelFreelancerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('CINEMATOGRAPHER', 'Cinematographer'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('SCRIPT_WRITER', 'Script Writer'), ('CAMERA_ASSISTANT', 'Camera Assistant'), ('PRODUCTION_HEAD', 'Production Head')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shootplan.crewmember')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_assignments', to='shootplan.reel')),
            ],
            options={
                'unique_together': {('reel', 'crew_member')},
            },
        ),
        migrations.RunPython(copy_existing_freelancer_assignments, noop_reverse),
        # Django disallows AlterField for adding `through=` to an M2M (it
        # raises "cannot alter to or from M2M fields, or add or remove
        # through=") -- must drop and recreate the field instead. Safe here
        # because every existing pairing was just copied into the new
        # through-model tables above, before the old implicit join table
        # this RemoveField drops is gone.
        migrations.RemoveField(model_name='photo', name='assigned_freelancers'),
        migrations.AddField(
            model_name='photo',
            name='assigned_freelancers',
            field=models.ManyToManyField(blank=True, related_name='photo_briefs', through='shootplan.PhotoFreelancerAssignment', to='shootplan.crewmember'),
        ),
        migrations.RemoveField(model_name='reel', name='assigned_freelancers'),
        migrations.AddField(
            model_name='reel',
            name='assigned_freelancers',
            field=models.ManyToManyField(blank=True, related_name='reels', through='shootplan.ReelFreelancerAssignment', to='shootplan.crewmember'),
        ),
    ]
