# Generated by Django 5.0.6 on 2026-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0020_photofreelancerassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('DOP', 'Director of Photography'), ('CAMERA', 'Camera Operator'), ('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('CINEMATOGRAPHER', 'Cinematographer'), ('CAMERA_ASSISTANT', 'Camera Assistant'), ('EDITOR', 'Editor'), ('STYLIST', 'Stylist'), ('MAKEUP', 'Hair & Makeup'), ('PRODUCTION_ASSISTANT', 'Production Assistant'), ('SCRIPT_WRITER', 'Script Writer'), ('SOCIAL_MEDIA_SPECIALIST', 'Social Media Specialist'), ('CLIENT_SERVICING', 'Client Servicing'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('PRODUCTION_HEAD', 'Production Head'), ('TALENT', 'Talent'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='source_brand_role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('DOP', 'Director of Photography'), ('CAMERA', 'Camera Operator'), ('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('CINEMATOGRAPHER', 'Cinematographer'), ('CAMERA_ASSISTANT', 'Camera Assistant'), ('EDITOR', 'Editor'), ('STYLIST', 'Stylist'), ('MAKEUP', 'Hair & Makeup'), ('PRODUCTION_ASSISTANT', 'Production Assistant'), ('SCRIPT_WRITER', 'Script Writer'), ('SOCIAL_MEDIA_SPECIALIST', 'Social Media Specialist'), ('CLIENT_SERVICING', 'Client Servicing'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('PRODUCTION_HEAD', 'Production Head'), ('TALENT', 'Talent'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
