# Generated by Django 5.0.6 on 2026-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootplan', '0021_alter_crewmember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobriefimage',
            name='category',
            field=models.CharField(choices=[('MOODBOARD', 'Moodboard'), ('WARDROBE', 'Wardrobe reference'), ('BACKGROUND', 'Background reference'), ('REFERENCE', 'Reference image')], default='MOODBOARD', max_length=20),
        ),
    ]
