# Generated by Django 5.0.6 on 2026-08-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_script_writer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRODUCTION_HEAD', 'Production Head'), ('SOCIAL_MEDIA', 'Social Media Specialist'), ('PRODUCTION_COORDINATOR', 'Production Coordinator'), ('CLIENT_SERVICING', 'Client Servicing'), ('SCRIPT_WRITER', 'Script Writer')], max_length=30),
        ),
    ]
